version: '4.37.1'
services:
  pdp-service:
    image: permitio/pdp-v2:latest
    ports:
      - '7766:7000'
    environment:
      - PDP_API_KEY=permit_key_ARMEMapcTNzZeJWKDsZyqSJUxgQes59quXMu89vyjSHdggtRUHTAy3CL0MQnlRnXAuffT8ERGKz9Yg1RiMRIDA
      - PDP_DEBUG=True
    stdin_open: true
    tty: true
